name: Deploy to kat server

# only run on changes to main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: tailscale connect pls
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.KAT_TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.KAT_TS_OAUTH_SECRET }}
          tags: tag:gh-ci

      - name: checkout repo
        uses: actions/checkout@v4

      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: build site
        run: |
          npm i
          npm run build

      - name: deploy to kat@athena
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.KATATHENA_GHDEPLOY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "_site/"
          REMOTE_HOST: "athena"
          REMOTE_USER: "kat"
          TARGET: "/var/www/scumsuck/justgorlythings/"
